name: Deploy Javadoc

on: [push]

jobs:
  build-javadoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
      run: ./gradlew javadoc
    - name: Build Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/docs/javadoc
  deploy-javadoc:
    needs: build-javadoc
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
